---
title: "Exploring income equality"
author: "Seven-Up"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
```

## Dataset

A brief description of your dataset including its provenance, dimensions, etc. as well as the reason why you chose this dataset.

Make sure to load the data and use inline code for some of this information.

The dataset comes from the Urban Institute and US Census and focuses on racial
wealth inequality. We chose this dataset because wealth inequality is a very
important issue in America, and it would be valuable to see the relationship
between race and wealth over time in America. There are around 5-6 data files
focused on the relationship between race and income over time. There are also
important files on the relationship between race and retirement, homeownership, 
and student debt. 
## Questions

The two questions you want to answer.

**Question 1: ** The first question we would like to explore is to see how
income distribution across different racial groups has changed over time. 

**Question 2: ** The second question we would like to explore is to see how 
homeownership has changed over time among different racial groups. 


## Analysis plan

A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).
