---
title: "eda-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-pkgs, message = F}
library(tidyverse)
library(viridis)
library(reprex)
library(gganimate)
library(gifski)
library(ggpubr)
library(magick)
```

```{r load-data, message = F}
income_mean <- read.csv(file = "../data/income_mean.csv")
home_owner <- read_csv(file = "../data/home_owner.csv")
race_wealth <- read_csv(file = "../data/race_wealth.csv")
```

```{r find-peaks}
lowest_year <- home_owner %>%
  group_by(year) %>%
  summarize(mean_pct_unweighted = mean(home_owner_pct)) %>%
  arrange(mean_pct_unweighted) %>%
  slice(1) %>%
  pull(year)
highest_year <- home_owner %>%
  group_by(year) %>%
  summarize(mean_pct_unweighted = mean(home_owner_pct)) %>%
  arrange(desc(mean_pct_unweighted)) %>%
  slice(1) %>%
  pull(year)  
lowest_year
highest_year
```


```{r first-look}
home_owner %>%
  ggplot(
    aes(x = year, y = home_owner_pct, color = race, shape = race)
  ) +
  geom_line() +
  geom_point(alpha = 0.5, size = 1) +
  geom_vline(aes(xintercept = lowest_year), color = "grey") +
  geom_vline(aes(xintercept = highest_year), color = "grey") +
  geom_label(x = lowest_year - 5, y = 0.56, 
            label = paste0("Year with lowest \nhome ownership (", lowest_year, ")"), 
            color = "black",
            label.size = NA) +
    geom_label(x = highest_year + 5, y = 0.56, 
            label = paste0("Year with highest \nhome ownership (", highest_year, ")"), 
            color = "black",
            label.size = NA) +
  # gganimate::transition_reveal(year) +
  scale_color_viridis_d() +
  labs(
    x = "Year",
    y = "Percent owning homes",
    color = "Race",
    shape = "Race",
    title = "Home ownership over time",
    subtitle = "by race"
  ) +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(scale = 100))
```
```{r static plot for before and after 2008 by 5 years}
 home_owner %>%
  filter(year > "2003", year <= "2010") %>%
  dplyr::group_by(year, race) %>%
  dplyr::summarise(avg_h_o = mean(home_owner_pct)) %>%
  ggplot(aes(x = as.factor(year), y = avg_h_o, fill = race))+ 
    geom_bar(width = 0.5, position="dodge", stat="identity") +
  coord_flip() +
  labs(title = "Homeownership 3 years before and after '06/'07 Housing Bubble",
       x = "Homeownership percentage",
       y = "Year")+
  geom_hline(aes(yintercept = 0.7207117), linetype = "dashed", alpha = 0.3)+
  geom_hline(aes(yintercept = 0.4816776), linetype = "dashed", alpha = 0.3)+
  geom_hline(aes(yintercept = 0.4930240), linetype = "dashed", alpha = 0.3) +
  scale_fill_viridis_d()
```


```{r second-look-data, cache = TRUE}

home_owner %>%
  filter(year >= "2003", year <= "2012") %>%
  dplyr::group_by(year, race) %>%
  ggplot(aes(x = race, y = home_owner_pct, fill = race))+ 
    geom_bar(position = "dodge", stat = "identity") +
  geom_text(aes(label=percent(home_owner_pct,accuracy=0.1)),
            position="stack",vjust= 2)+
  geom_point()+
scale_fill_viridis_d() +
  labs(
    x = "Year",
    y = "Percent owning homes",
    color = "Race",
    shape = "Race",
subtitle = "Homeownership 5-6 years before and after '06/'07 Housing Bubble by race"
  ) +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  transition_time(year)+
  labs(title = "Year: {frame_time}")



```

```{r explore-homeowner-with-wealth}
race_wealth <- race_wealth %>%
  filter(type == "Average") %>%
  drop_na() %>%
  group_by(race, year)

race_wealth

ggplot(race_wealth, aes(x = year, y = wealth_family, color = race)) +
  geom_point() +
  geom_line() +
  geom_vline(aes(xintercept = lowest_year), color = "grey", size = 1) +
  geom_vline(aes(xintercept = highest_year), color = "grey", size = 1) +
  theme_minimal()
```

