---
title: "Income and home-ownership over time"
subtitle: "By race"
author: "Team 7-Up <br> Blossom Mojekwu, Kartik Chamarti, Margaret Reed, Phillip Harmadi"
institute: "Duke University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r load-packages, include = FALSE}
library(tidyverse)
library(knitr)
library(viridis)
library(xaringanthemer)
library(ggrepel)
```

```{r setup, include = FALSE}
# For better figure resolution
knitr::opts_chunk$set(
  fig.retina = 3, 
  dpi = 300, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "70%"
  )
```

```{r load-data, include = FALSE}
income_mean <- read_csv(file = "../data/income_mean.csv")
home_owner <- read_csv(file = "../data/home_owner.csv")
```

```{r style-slides, echo = FALSE}
style_xaringan(
  title_slide_background_image = "img/watercolour_sys02_img34_teacup-ocean.jpg"
)
```

Class: middle, inverse, center

# Intro

---

# The data

---

# Question 1

How has home-ownership changed over time, and how does this trend vary between 
different races?

---

```{r find-peaks, include = FALSE}
lowest_year <- home_owner %>%
  group_by(year) %>%
  summarize(mean_pct_unweighted = mean(home_owner_pct)) %>%
  arrange(mean_pct_unweighted) %>%
  slice(1) %>%
  pull(year)
highest_year <- home_owner %>%
  group_by(year) %>%
  summarize(mean_pct_unweighted = mean(home_owner_pct)) %>%
  arrange(desc(mean_pct_unweighted)) %>%
  slice(1) %>%
  pull(year)

last_year <- home_owner %>%
  group_by(race) %>%
  filter(year == max(year))
```


```{r first-look, echo = FALSE}
home_owner %>%
  ggplot(
    aes(x = year, y = home_owner_pct, color = race)
  ) +
  geom_line(size = 1) +
  geom_point(alpha = 0.5, size = 1.5, aes(shape = race)) +
  geom_vline(aes(xintercept = lowest_year), color = "grey") +
  geom_vline(aes(xintercept = highest_year), color = "grey") +
  annotate(geom = "text",
    x = lowest_year - 5, 
    y = 0.56,
    label = paste0("Year with lowest \nhome ownership (", lowest_year, ")"),
    color = "black"
    ) +
  annotate(
    geom = "text",
    x = highest_year + 5, 
    y = 0.56, 
    label = paste0("Year with highest \nhome ownership (", highest_year, ")"), 
    color = "black"
    ) +
  geom_text_repel(
    data = last_year,
    aes(label = race),
    direction = "y",
    nudge_x = 2,
    nudge_y = 0.03,
    size = 4,
    segment.linetype = "dotted"
    ) +
  scale_color_manual(values = c("#859a6a", "#ad6e72", "#5d7a96")) +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  labs(
    x = "Year",
    y = "Percent owning homes",
    color = "Race",
    shape = "Race",
    title = "Home ownership over time",
    subtitle = "by race",
    caption = "7 Up: Blossom Mojekwu, Kartik Chamarti, Margaret Reed, Phillip Harmadi"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
```

---
# Question 2

What does household income level look like for each racial group over time, and 
how do household income disparities compare among different racial groups?

---

```{r data-wrangle-2, include = FALSE}
income_mean <- income_mean %>%
  filter(!str_detect(race, "Combination"),
         !str_detect(race, "Not Hispanic"),
         !str_detect(race, "All"),
         dollar_type == "2019 Dollars",
         income_quintile != "Top 5%") %>%
  group_by(year, race, income_quintile) %>%
  summarize(income_dollars =  mean(income_dollars), 
            .groups = "drop") %>%
  mutate(race = str_remove(race, ',?\\s(.*)'),
         income_quintile = ordered(income_quintile, c("Lowest", "Second", 
                                                      "Middle", "Fourth", 
                                                      "Highest")),
      income_percentile = case_when(
        income_quintile == "Top 5%"   ~ "1st - 5th",
        income_quintile == "Highest"  ~ "Top 20%",
        income_quintile == "Fourth"   ~ "21-40 %",
        income_quintile == "Middle"   ~ "41-60 %",
        income_quintile == "Second"   ~ "61-80 %",
        income_quintile == "Lowest"   ~ "Bottom 20%"),
        income_percentile = ordered(income_percentile, 
                                  c("Bottom 20%", "61-80 %", "41-60 %", 
                                    "21-40 %", "Top 20%")))
```

```{r perc-plot, include = FALSE}
highest_perc_table <- income_mean %>%
  filter(year == 2019) %>%
  group_by(race) %>%
  transmute(income_quintile, percent = income_dollars/sum(income_dollars)) %>%
  filter(income_quintile == "Highest")
```

```{r plot-overtime, echo = FALSE}
income_mean %>%
  ggplot(
    aes(x = year, y = income_dollars, color = income_percentile)
  ) +
  geom_line() +
  facet_wrap(.~race, nrow = 1) +
  scale_y_continuous(labels = scales::label_number(big.mark = ",", 
                                                   scale = 0.001, 
                                                   suffix = "k",
                                                   prefix = "$")) +
  scale_color_manual(values = c("grey40", "grey50", "grey60", "grey70", 
                                "firebrick2")) +
  labs(
    title = "Income Gap: How does income distribution compare for each race?",
    subtitle = "By income quintile",
    x = "Year", 
    y = "Mean household income", 
    color = "Income quintile",
    caption = "7 Up: Blossom Mojekwu, Kartik Chamarti, Margaret Reed, Phillip Harmadi"
    ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

---

```{r plot-bar, echo = FALSE}
income_mean %>%
  filter(year == 2019) %>%
  ggplot(
    aes(x = income_dollars,
        y = reorder(race, desc(race)))
    ) + 
  geom_bar(
    position = "fill", 
    stat = "identity", 
    aes(fill = reorder(income_percentile, desc(income_percentile)))
    ) +
  geom_text(
    data = highest_perc_table, 
    aes(
      y = race, label = paste0(round(percent, 2)*100, "%")),
    x = 0.8, 
    color = "white") +
  scale_fill_brewer(type = "seq", palette = "Blues", direction = -1) +
  labs(
    title = "Income Gap: How much do top households earn compared to bottom households \nfor each race?",
    subtitle = "In 2019",
    x = "Percent of total mean income", 
    y = "Race", 
    fill = "Income Quintile",
    caption = "7 Up: Blossom Mojekwu, Kartik Chamarti, Margaret Reed, Phillip Harmadi"
    ) +
  scale_colour_viridis_d() +
  scale_x_continuous(labels = scales::percent_format(scale = 100)) +
  theme_minimal(base_size = 10) +
  theme(text = element_text(size = 9))
```

---

# Thank you!

---





