---
title: "Final Viz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-pkgs, message = F}
library(tidyverse)
library(viridis)
library(ggrepel)
library(ggthemes)
# library(gganimate)
```

```{r load-data, message = F}
income_mean <- read_csv(file = "../data/income_mean.csv")
home_owner <- read_csv(file = "../data/home_owner.csv")
```

### Question 1

```{r find-peaks}
lowest_year <- home_owner %>%
  group_by(year) %>%
  summarize(mean_pct_unweighted = mean(home_owner_pct)) %>%
  arrange(mean_pct_unweighted) %>%
  slice(1) %>%
  pull(year)
highest_year <- home_owner %>%
  group_by(year) %>%
  summarize(mean_pct_unweighted = mean(home_owner_pct)) %>%
  arrange(desc(mean_pct_unweighted)) %>%
  slice(1) %>%
  pull(year)

last_year <- home_owner %>%
  group_by(race) %>%
  filter(year == max(year))
```

#### Plot 1.a
```{r first-look}
home_owner %>%
  ggplot(
    aes(x = year, y = home_owner_pct, color = race, shape = race)
  ) +
  geom_line(size = 1) +
  geom_point(alpha = 0.5, size = 1.5) +
  geom_vline(aes(xintercept = lowest_year), color = "grey") +
  geom_vline(aes(xintercept = highest_year), color = "grey") +
  annotate(geom = "text",
    x = lowest_year - 5, 
    y = 0.56,
    label = paste0("Year with lowest \nhome ownership (", lowest_year, ")"),
    color = "black"
    ) +
  annotate(
    geom = "text",
    x = highest_year + 5, 
    y = 0.56, 
    label = paste0("Year with highest \nhome ownership (", highest_year, ")"), 
    color = "black"
    ) +
  geom_text_repel(data = last_year,
                  aes(label = race),
                  direction = "y",
                  nudge_x = 2,
                  nudge_y = 0.02,
                  size = 5,
                  segment.linetype = "dotted") +
  scale_color_manual(values = c("#859a6a", "#ad6e72", "#5d7a96")) +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  labs(
    x = "Year",
    y = "Percent owning homes",
    color = "Race",
    shape = "Race",
    title = "Home ownership over time",
    subtitle = "by race"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
```



### Question 2

```{r data-wrangle-2}
income_mean <- income_mean %>%
  filter(!str_detect(race, "Combination"),
         !str_detect(race, "Not Hispanic"),
         !str_detect(race, "All"),
         dollar_type == "2019 Dollars",
         income_quintile != "Top 5%") %>%
  group_by(year, race, income_quintile) %>%
  summarize(income_dollars =  mean(income_dollars), 
            .groups = "drop") %>%
  mutate(race = str_remove(race, ',?\\s(.*)'),
         income_quintile = ordered(income_quintile, c("Lowest", "Second", 
                                                      "Middle", "Fourth", 
                                                      "Highest")),
      income_percentile = case_when(
        income_quintile == "Top 5%"   ~ "1st - 5th",
        income_quintile == "Highest"  ~ "Top 20%",
        income_quintile == "Fourth"   ~ "21-40 %",
        income_quintile == "Middle"   ~ "41-60 %",
        income_quintile == "Second"   ~ "61-80 %",
        income_quintile == "Lowest"   ~ "Bottom 20%"),
      income_percentile = ordered(income_percentile, 
                                  c("Bottom 20%", "61-80 %", "41-60 %", 
                                    "21-40 %", "Top 20%")),
      race = ordered(race, c("White", "Black", "Hispanic", "Asian")))
  
```

```{r perc-plot}
highest_perc_table <- income_mean %>%
  filter(year == 2019) %>%
  group_by(race) %>%
  transmute(income_quintile, percent = income_dollars/sum(income_dollars)) %>%
  filter(income_quintile == "Highest")
perc_21_40_perc_table <- income_mean %>%
  filter(year == 2019) %>%
  group_by(race) %>%
  transmute(income_quintile, percent = income_dollars/sum(income_dollars)) %>%
  filter(income_quintile == "Fourth")
perc_41_60_perc_table <- income_mean %>%
  filter(year == 2019) %>%
  group_by(race) %>%
  transmute(income_quintile, percent = income_dollars/sum(income_dollars)) %>%
  filter(income_quintile == "Middle")
perc_61_80_perc_table <- income_mean %>%
  filter(year == 2019) %>%
  group_by(race) %>%
  transmute(income_quintile, percent = income_dollars/sum(income_dollars)) %>%
  filter(income_quintile == "Second")
bottom_perc_table <- income_mean %>%
  filter(year == 2019) %>%
  group_by(race) %>%
  transmute(income_quintile, percent = income_dollars/sum(income_dollars)) %>%
  filter(income_quintile == "Lowest")
```



#### Plot 2.a

```{r plot-overtime, , fig.width = 8, fig.length = 5}

plot_2a <- income_mean %>%
  ggplot(
    aes(x = year, y = income_dollars, color = income_percentile)
  ) +
  geom_line() +
  facet_wrap(.~race, nrow = 1) +
  scale_y_continuous(labels = scales::label_number(big.mark = ",", 
                                                   scale = 0.001, 
                                                   suffix = "k",
                                                   prefix = "$")) +
  scale_color_manual(values = c("grey40", "grey50", "grey60", "grey70", 
                                "firebrick2")) +
  labs(
    title = "Income Gap: How does income distribution compare for each race?",
    subtitle = "per income quintile in time series",
    x = "Year", 
    y = "Mean household income", 
    color = "Income quintile",
    caption = "Source: U.S. Census 2019 Data"
    ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.x.bottom = element_text(angle = 90)) +
  guides(color = guide_legend(reverse = TRUE))

plot_2a

ggsave("plot_2a.png")
```

#### Plot 2.b

```{r plot-bar, fig.width = 8, fig.length = 6}

plot_2b <- income_mean %>%
  filter(year == 2019) %>%
  ggplot(
    aes(x = income_dollars,
        y = reorder(race, desc(race)))
    ) + 
  geom_bar(
    position = "fill", 
    stat = "identity", 
    aes(fill = income_percentile),
    width = 0.7
    ) +
  geom_text(
    data = highest_perc_table, 
    aes(y = race, 
        label = paste0(round(percent, 3)*100)),
        x = 0.45, size = 2.5,
        color = "black",
        nudge_x = 0, nudge_y = -0.45) +
  geom_text(
    data = perc_21_40_perc_table, 
    aes(y = race, 
        label = paste0(round(percent, 3)*100)),
        x = 0.65, size = 2.5,
        color = "black",
        nudge_x = 0, nudge_y = -0.45) +
  geom_text(
    data = perc_41_60_perc_table, 
    aes(y = race, 
        label = paste0(round(percent, 3)*100)),
        x = 0.80, size = 2.5,
        color = "black",
        nudge_x = 0, nudge_y = -0.45) +
  geom_text(
    data = perc_61_80_perc_table, 
    aes(y = race, 
        label = paste0(round(percent, 3)*100)),
        x = 0.92, size = 2.5,
        color = "black",
        nudge_x = 0, nudge_y = -0.45) +
  geom_text(
    data = bottom_perc_table, 
    aes(y = race, 
        label = paste0(round(percent, 3)*100)),
        x = 0.975, size = 2.5,
        color = "black",
        nudge_x = 0, nudge_y = -0.45) +
  scale_fill_brewer(type = "seq", palette = "Blues", direction = -1) +
  labs(
    title = "Income Gap: How much do top quintile households earn compared to other quintiles?",
    subtitle = "Proportion of income earned for each household quintile per race",
    x = "Percentage %", 
    y = "Race", 
    fill = "Income Quintile",
    caption = "Source: U.S. Census 2019 Data"
    ) +
  scale_colour_viridis_d() +
  scale_x_continuous(labels = scales::label_number(big.mark = ",", 
                                                   scale = 100, 
                                                   suffix = "",
                                                   prefix = ""),
                     breaks = seq(-0.2, 1.2, 0.2)) +
  # scale_x_continuous(labels = scales::percent_format(scale = 100)) +
  theme_minimal(base_size = 10) +
  theme(text = element_text(size = 9),
        axis.title.x = element_text(vjust = -2),
        plot.caption = element_text(vjust = -3, hjust = 0)) +
  guides(fill = guide_legend(reverse = TRUE))

plot_2b

ggsave("plot_2b.png")
```




